name: TextArt
main: online.fireflower.text_art.TextArt
author: Fire
version: 1.0.0.0
description: Used to create text based builds in game
depend:
  - WorldEdit
commands:
  write:
    permission: "TextArt.write"
    permission-message: "You do not have permission textArt.write"
    usage: "/draw Ping Spoofing"
  draw:
    permission: "TextArt.draw"
    permission-message: "You do not have permission textArt.draw"
    usage: "/draw url"